Attempt to handle existing migration branch properly

diff --git a/.github/workflows/migrate.yaml b/.github/workflows/migrate.yaml
--- a/.github/workflows/migrate.yaml
+++ b/.github/workflows/migrate.yaml
@@ -31,8 +31,7 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip uv
-          uv pip install --system testing.postgresql alembic sqlalchemy pyyaml black psycopg2-binary
-          uv pip install --system 'lsst-felis @ git+http://github.com/lsst/felis.git@tickets/DM-46130'
+          uv pip install --system lsst-felis testing.postgresql alembic sqlalchemy pyyaml black psycopg2-binary
 
       - name: Determine branch name and commit SHA
         run: |
@@ -54,9 +53,9 @@ jobs:
 
       - name: Check branch name
         run: |
-          if [[ ! "${{ env.BRANCH_NAME }}" =~ ^tickets/DM-[0-9]+(-[a-zA-Z0-9-]*)?$ ]]; then
+          if [[ ! "${{ env.BRANCH_NAME }}" =~ ^tickets/DM-[0-9]+([a-zA-Z0-9-]*)?$ ]]; then
             echo "Bad branch name: ${{ env.BRANCH_NAME }}" >&2
-            echo "Error: Migrations are only generated for branches matching the pattern 'tickets/DM-[number](-[alphanumeric-]*)'." >&2
+            echo "Error: Migrations are only generated for branches matching the pattern 'tickets/DM-[number]([alphanumeric-]*)'." >&2
             exit 1
           fi
 
@@ -76,6 +75,19 @@ jobs:
           repository: lsst/sdm_schemas
           ref: ${{ env.COMMIT_SHA }}
           path: sdm_schemas
+
+      - name: Check for existing migration branch and reset it
+        working-directory: consdb
+        run: |
+          MIGRATION_BRANCH_NAME=${{ env.BRANCH_NAME }}-migrate
+          git fetch origin
+          if git show-ref --verify --quiet refs/heads/${MIGRATION_BRANCH_NAME}; then
+            echo "Branch ${MIGRATION_BRANCH_NAME} already exists. Resetting it to main."
+            git checkout ${MIGRATION_BRANCH_NAME}
+            git reset --hard origin/main
+            git push --force origin ${MIGRATION_BRANCH_NAME}
+          fi
+          echo "MIGRATION_BRANCH_NAME=$MIGRATION_BRANCH_NAME" >> $GITHUB_ENV
 
       - name: Generate the migration scripts
         working-directory: ${{ github.workspace }}/consdb
@@ -103,7 +115,7 @@ jobs:
             ## Checklist
 
             - [ ] Verified the automatically generated migration scripts
-          branch: ${{ env.BRANCH_NAME }}-migrate
+          branch: ${{ env.MIGRATION_BRANCH_NAME }}
           base: main
           draft: true
           labels: migration
